##1. Create a 3*3 NumPy array with random Integers b/w 1 and 100. Then Interchange its rows and coloumn

In [ ]:
#A NumPy array with random Integers b/w 1 and 100.
import numpy as np
x = np.random.randint(1,100,(3,3))
print(x)

y = x.T
print(y)

[[97 72 94]
 [36 53 20]
 [31 10  8]]
[[97 36 31]
 [72 53 10]
 [94 20  8]]


##2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2 * 5 array, then into a 5 * 2 array.

In [ ]:
# NumPy array with 10 elements. Reshape it into a 2 * 5 array, then into a 5 * 2 array.
a = np.arange(10)
print(a)
b = a.reshape(2,5)
print(b)
c = a.reshape(5,2)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


##3. Create a 4 * 4 NumPy array with random float values.Add a border of zeros around it, resulting in a 6 * 6 array.

In [ ]:
#a 4 * 4 NumPy array with random float values.Add a border of zeros around it, resulting in a 6 * 6 array.
d = np.random.random((4,4))
print(d)
e = np.pad(d, pad_width=1, mode='constant', constant_values=0)
print(e)

[[0.76903816 0.62263122 0.059928   0.17547041]
 [0.59443875 0.03847673 0.04896803 0.15739763]
 [0.13988218 0.92878329 0.48941515 0.64372937]
 [0.47915013 0.8618695  0.67582129 0.88458206]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.76903816 0.62263122 0.059928   0.17547041 0.        ]
 [0.         0.59443875 0.03847673 0.04896803 0.15739763 0.        ]
 [0.         0.13988218 0.92878329 0.48941515 0.64372937 0.        ]
 [0.         0.47915013 0.8618695  0.67582129 0.88458206 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


##4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.


In [ ]:
# create an arry of integers from 10 to 60 with a step of 5.
f = np.arange(10,60,5)
print(f)

[10 15 20 25 30 35 40 45 50 55]


##5. Create a NumPy array of strings['python','numpy','pandas']. Apply different case transformation (uppercase,lowercase,title case,etc) to each statement.

In [13]:
# Create a NumPy array of strings
arr = np.array(['Python', 'nUmpy', 'paNdas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

print(uppercase_arr)
print(lowercase_arr)
print(titlecase_arr)


['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


##6. Generate a NumPy array of words. Insert a space b/w each character of every word in the array.

In [16]:
# Insert a space b/w each character of every word in the array.
g = np.array(['python', 'numpy', 'pandas'])
h = np.char.join(' ', g)
print(h)


['p y t h o n' 'n u m p y' 'p a n d a s']


##7. Create two 2D NumPy arrays and perform element-wise addtion, subtraction, multiplication, and division.


In [21]:
#Create two 2D NumPy arrays and perform element-wise addtion, subtraction, multiplication, and division

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise multiplication
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise addition:")
print(addition)

print("\nElement-wise subtraction:")
print(subtraction)

print("\nElement-wise multiplication:")
print(multiplication)

print("\nElement-wise division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


##8. Use NumPy to create a 5 * 5 identity matrix, then extract diagonal elements.


In [26]:
# create a 5 * 5 identity matrix, then extract diagonal elements.
i = np.eye(5)
print(i)

diagonal_elements = np.diag(i)
print(diagonal_elements)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


##9. Generates a NumPy array of 100 random integers b/w 0 and 1000. Find and display all prime numbers in array.

In [27]:
#array of 100 random integers b/w 0 and 1000. Find and display all prime numbers in array.

import numpy as np

# Generate array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, 100)

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    elif num <= 3:
        return True
    elif num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

# Find prime numbers in the array using vectorized approach
prime_mask = np.vectorize(is_prime)(random_integers)
prime_numbers = random_integers[prime_mask]

# Print the original array and prime numbers
print("Original array:")
print(random_integers)

print("\nPrime numbers in the array:")
print(prime_numbers)


Original array:
[ 62 399 250  29 785 252 446 483 649 163 597 524 313 128 709 442 523 680
 323 869  62 253 246 739 323 130 257 478  28 869 757 373 164 187 989 325
 989 456 982 250 682 861 661 263 891 475 281  91 925 203 291 363 486 681
  39 693 815 985 558 640 120 600 617 924 380  29 510 875 196 851  34 251
 206 305 326 387 184 920 770 731 256 719 900 960 109 438 305   4 292 400
  57  36 265 961 637 667 917 576 678 630]

Prime numbers in the array:
[ 29 163 313 709 523 739 257 757 373 661 263 281 617  29 251 719 109]


##10. Create a Numpy array representing daily tempretures for a month. Calculate and display the weekly averages.

In [34]:
# Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

np.random.seed(0)

daily_temperatures = np.random.randint(10, 30, size=(35,))

print("Daily Temperatures:")
print(daily_temperatures)

weekly_averages = np.mean(daily_temperatures.reshape(-1, 7), axis=1)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures:
[22 25 10 13 13 17 19 29 28 14 16 22 11 16 17 24 27 15 23 18 19 29 26 29
 15 25 25 10 28 13 27 29 29 29 24]

Weekly Averages:
[17.         19.42857143 20.42857143 22.71428571 25.57142857]
